"""Textos compartidos entre el bot y el servidor de OAuth."""

# Mensaje de bienvenida corto (apenas conecta Google). En vez del manual completo,
# ejemplos concretos para que pruebe YA. El manual completo queda a un botón.
BIENVENIDA_CONECTADO = (
    "🎉 *¡Listo! Ya podés usar Sebastian.*\n\n"
    "Escribime como le hablarías a una persona. Probá mandándome, por ejemplo:\n\n"
    "📋 *comprar pan* → te lo anoto como tarea\n"
    "📅 *reunión el viernes a las 10* → lo agendo\n"
    "💸 *gasté 5000 en el súper* → lo registro\n"
    "⏰ *recordame llamar al médico mañana a las 3*\n\n"
    "También entiendo *audios* 🎤 y *fotos* de tickets 📷.\n\n"
    "Probá con cualquiera ahora mismo 👇"
)

# Manual corto que se abre desde el botón al pie de la lista de tareas.
# Solo lo esencial del día a día; el botón de abajo abre INSTRUCCIONES_TEXTO completo.
MANUAL_TAREAS = (
    "📖 *Guía rápida*\n\n"
    "*📋 Tareas*\n"
    "• Anótelas hablando: \"anotá comprar pan\", \"tengo que llamar al médico\"\n"
    "• A mano: un punto adelante → \".comprar pan\"\n"
    "• Con vencimiento: \"agregá pagar la luz, vence el lunes\"\n"
    "• Verlas: \"mostrame la lista\" (o \".tareas\")\n"
    "• Eliminar: punto y número → \".2\" (o \"borrá la tarea 2\")\n"
    "• Editar: \"renombrá la tarea 1...\", \"ponele fecha el viernes a la tarea 3\"\n\n"
    "*⏰ Recordatorios*\n"
    "• \"recordame llamar al médico mañana a las 3\"\n"
    "• \"avisame a las 18 que saque la carne\"\n"
    "• \"mis recordatorios\" para verlos o cancelarlos\n\n"
    "*📅 Eventos (calendario)*\n"
    "• Crear: \"agendá reunión el viernes a las 10\" (le aviso si se pisa con otro)\n"
    "• Ver: \"qué tengo hoy\", \"qué tengo el martes\"\n"
    "• Editar/eliminar: \"cambiá la hora de la reunión\", \"eliminá el evento X\"\n"
    "• Le aviso ~30 min antes de cada evento ⏰\n\n"
    "*🤔 ¿Tarea, recordatorio o evento?*\n"
    "• Sin hora → 📋 *tarea* (queda en su lista). Ej: \"comprar pan\"\n"
    "• \"recordame/avisame\" + una hora → ⏰ *recordatorio* (le aviso a esa hora)\n"
    "• Una cita o reunión con día y hora → 📅 *evento* (va al calendario)"
)

INSTRUCCIONES_TEXTO = (
    "📖 *Guía de Sebastian*\n\n"
    "A su servicio. Hábleme con naturalidad —por texto o audio 🎤— o envíeme "
    "una foto 📷, que yo me encargo. Esto es todo aquello en lo que puedo "
    "asistirle:\n\n"
    "*📋 Tareas*\n"
    "• Anótelas hablando: \"anotá comprar pan\", \"tengo que llamar al médico\"\n"
    "• A mano: un punto adelante → \".comprar pan\"\n"
    "• Con vencimiento: \"agregá pagar la luz, vence el lunes\"\n"
    "• Verlas: \"mostrame la lista\" (o \".tareas\")\n"
    "• Eliminar: punto y número → \".2\" (o \"borrá la tarea 2\")\n"
    "• Editar: \"renombrá la tarea 1...\", \"ponele fecha el viernes a la tarea 3\"\n\n"
    "*💸 Gastos*\n"
    "• Registrar: \"gasté 5000 en el súper\", \"pagué 12000 de luz\"\n"
    "• Por foto del ticket 📷 → lo cargo solo\n"
    "• Consultar: \"cuánto gasté este mes\", \"gastos de transporte\"\n"
    "• Editar/borrar: \"cambiá el monto del 1 a 4500\", \"borrá el gasto 2\"\n\n"
    "*🔁 Gastos fijos* (los cargo solos cada mes)\n"
    "• \"el alquiler son 200000 por mes\", \"gasto fijo Netflix 5000\"\n"
    "• \"cuáles son mis gastos fijos\", \"cancelá el gasto fijo del club\"\n\n"
    "*💰 Ingresos y balance*\n"
    "• \"cobré 150000\" → registro el ingreso\n"
    "• \"cuál es mi balance\", \"cuánto me queda este mes\"\n\n"
    "*💳 Deudas*\n"
    "• \"le debo 30000 a Vero\", \"Caro me debe 5000\"\n"
    "• \"cuánto debo\", \"mis deudas\", \"saldé la deuda 1\"\n\n"
    "*🛒 Lista del súper*\n"
    "• \"agregá leche y pan a la lista del súper\"\n"
    "• \"pasame la lista del súper\" → se la muestro con un botón ➕\n"
    "• En modo agregar puede dictar muchos de una vez (uno por línea o con "
    "comas) y decir \"listo\"\n\n"
    "*📝 Listados*\n"
    "• \"armame una lista de viaje con protector, ojotas y toalla\"\n"
    "• \"mostrame el listado del viaje\", \"mis listados\"\n\n"
    "*⏰ Recordatorios*\n"
    "• \"recordame llamar al médico mañana a las 3\"\n"
    "• \"avisame a las 18 que saque la carne\"\n"
    "• \"mis recordatorios\" para verlos o cancelarlos\n\n"
    "*📅 Eventos (calendario)*\n"
    "• Crear: \"agendá reunión el viernes a las 10\" (le aviso si se pisa con otro)\n"
    "• Ver: \"qué tengo hoy\", \"qué tengo el martes\"\n"
    "• Editar/eliminar: \"cambiá la hora de la reunión\", \"eliminá el evento X\"\n"
    "• Le aviso ~30 min antes de cada evento ⏰\n\n"
    "*🤔 ¿Tarea, recordatorio o evento?*\n"
    "• Sin hora → 📋 *tarea* (queda en su lista). Ej: \"comprar pan\"\n"
    "• \"recordame/avisame\" + una hora → ⏰ *recordatorio* (le aviso a esa hora)\n"
    "• Una cita o reunión con día y hora → 📅 *evento* (va al calendario)\n\n"
    "*📲 Menú y configuración*\n"
    "• /menu abre todo con botones\n"
    "• En Configuración elige cómo prefiere que lo trate (señor/señora)\n\n"
    "Cada mañana a las 8:00 le haré llegar el resumen de su día. ☀️ "
    "Quedo a su entera disposición."
)
